{"uuid": "2aa8a7a0-563d-4e68-b591-3430ec1e462a", "children": ["13a410e1-bb9a-4cfa-8249-a61c6734c310", "2fbea170-4108-4693-a031-b94e06fb9f93", "2f5b43e5-ce6e-4b02-bc9f-14274ad58188", "ac48a1b7-1129-457b-9a1a-a6b93cddd2dd", "f43083e6-7c27-4f2a-9466-e36dc66ff1e6", "c54981c8-59c4-4010-80d1-be0583c2d3f9"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'in.amazon.mShop.android.shopping' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.amazon.mShop.home.HomeActivity' or 'in.amazon.mShop.android.shopping.com.amazon.mShop.home.HomeActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'in.amazon.mShop.android.shopping' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.amazon.mShop.home.HomeActivity' or 'in.amazon.mShop.android.shopping.com.amazon.mShop.home.HomeActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\n    at getResponseForW3CError (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.getDriverMethod()\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\base\\DriverClass.py\", line 15, in getDriverMethod\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 274, in __init__\n    super().__init__(\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1653736649141, "stop": 1653736685407}], "start": 1653736649141, "stop": 1653736686507}