{"uuid": "c7509760-0c5b-4b5e-8b18-6ea158ef3cab", "children": ["76aa300a-6ec7-429a-90bf-ec4ed52efdaf", "c92c3585-9687-4182-a037-15d9b4bf272b", "1144b5ba-cb05-4fec-bd2e-7bb6e576fc61", "6c219a2e-305b-43d8-bcd3-590d0e7f3da7", "3a5df307-f40c-45b4-b732-8896a1d2f2ca", "c8b35039-fb9c-49cd-92d9-bc90d62cf738"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'in.amazon.mShop.android.shopping' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.amazon.mShop.home.HomeActivity' or 'in.amazon.mShop.android.shopping.com.amazon.mShop.home.HomeActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'in.amazon.mShop.android.shopping' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: 'com.amazon.mShop.home.HomeActivity' or 'in.amazon.mShop.android.shopping.com.amazon.mShop.home.HomeActivity' never started. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting\n    at getResponseForW3CError (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.getDriverMethod()\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\base\\DriverClass.py\", line 15, in getDriverMethod\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 274, in __init__\n    super().__init__(\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\150182\\PycharmProjects\\Appium_Project\\Amazon_Pom\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1653736792247, "stop": 1653736827140}], "start": 1653736792247, "stop": 1653736827766}